apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: swiftcloud-identity-ui-tls
spec:
  secretName: swiftcloud-identity-ui-tls
  dnsNames:
  - identity.swiftcloud.co.zm
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
